### ISSUE TITLE
Copy Better - Copy without empty lines request

### ISSUE THREAD

**Issue by Lapka0** [kodango/copybetter#17]
Hi, 3 months ago I posted this also on http://kodango.com/copybetter-extension#comment, but no response:  Could you please add to the Chrome extention an option, that from selected and copied text are removed extra empty lines, which is already an option in a Firefox add-on called AutocopySelection2Clipboard. But Firefox is for me too slow on loading some websites. I have searched a lot for such feature in Chrome, but not found. It would be very heplfull, because I am copying a lot of numbers from chrome to excel and dont want to have empty rows.

**Comment by kodango** [comment]
already added
